name: NuGet

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: NuGet Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
            
      - name: Build
        run: dotnet build --configuration Release
        
      - name: Package
        run: >
          dotnet pack --no-restore --no-build --configuration Release 
          -p:PackageVersion=${{ github.ref_name }} --output .
        
      - name: Publish
        run: >
          dotnet nuget push PackageUtils.${{ github.ref_name }}.nupkg 
          -s https://nuget.pkg.github.com/reniciuspagotto/index.json 
          -k ${{ secrets.PACKAGES }}
